# Config file for MegaMan 64 Recompilation.

[input]
entrypoint = 0x80025C00
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
symbols_file_path = "megaman64.us.rev1.syms.toml"
#elf_path = "megaman64.elf"
rom_file_path = "MegaMan64.z64"

manual_funcs = [
]

[patches]
stubs = [
	# Stub function that checks player status?
	"func_80092EB0_6E2B0",
	"Graph_ThreadStop",
	"func_80087590_62990"
]

ignored = [
]

# Hooks
[[patches.hook]]
before_vram = 0x80027404
func = "Overlay_Loader"
text = "load_overlays(ctx->r18, ctx->r16, ctx->r17);"

# Single-instruction patches
[[patches.instruction]]
func = "func_8008A02C_6542C"
vram = 0x8008A0E4
value = 0x08022839 #jump to self, pause_self
