# Config file for MegaMan 64 Recompilation.

[input]
entrypoint = 0x80025C00
output_func_path = "RecompiledFuncs"
symbols_file_path = "MegaMan64RecompSyms/megaman64.us.rev1.syms.toml"
rom_file_path = "megaman64.us.z64"

manual_funcs = [
]

[patches]
stubs = [
	"func_80092EB0_6E2B0", # Stub function that checks RSP status?
	"Graph_ThreadStop", # Function that stops the graphics thread
	"func_80087590_62990" # Function that starts the graphics thread
]

ignored = [
]

# Hooks

#Overlay loading
[[patches.hook]]
func = "Overlay_Loader"
before_vram = 0x80027404
text = "recomp_load_overlays(rdram, ctx);"

#Fix to yield main thread
[[patches.hook]]
func = "func_8008A02C_6542C"
before_vram = 0x8008A0E8
text = "yield_self(rdram);"


##Reduce Fog thickness
#[[patches.instruction]]
#func = "func_800276EC_2AEC"
#vram = 0x80027C68
#value = 0x34841400 # ori $a0, $a0, 0xF400